### ISSUE TITLE
Doable now?

### ISSUE THREAD

**Issue by EthnTuttle** [BlockstreamResearch/cross-input-aggregation#18]
Is this doable with libsecp256k1 as is currently?

**Comment by jonasnick** [comment]
There's a module in libsecp256k1-zkp that provides [half-aggregation](https://github.com/BlockstreamResearch/secp256k1-zkp/blob/master/include/secp256k1_schnorrsig_halfagg.h).

**Comment by EthnTuttle** [comment]
I assume this means full aggregation is still lacking?

**Comment by EthnTuttle** [comment]
I suppose a better question would be: is full aggregation being worked on anywhere? Is there a reference document or something I can study to better understand it?

**Comment by real-or-random** [comment]
> is full aggregation being worked on anywhere?

Not that we're aware of.


> Is there a reference document or something I can study to better understand it?

https://cisaresearch.org/ is the best resource for getting started, but there's not much more on full aggregation.
