### ISSUE TITLE
Hash input inconsistent

### ISSUE THREAD

**Issue by b-wagn** [BlockstreamResearch/cross-input-aggregation#9]
[Input for hash in rust code](https://github.com/BlockstreamResearch/cross-input-aggregation/blob/master/hacspec-halfagg/src/halfagg.rs#L27) is inconsistent with [input for hash in pseudocode](https://github.com/BlockstreamResearch/cross-input-aggregation/blob/master/half-aggregation.mediawiki#user-content-Pseudocode).

- Rust code says "pk,mes,r"
- Pseudocode says "r,pk,mes"

**Comment by jonasnick** [comment]
Thanks! Fixed in https://github.com/BlockstreamResearch/cross-input-aggregation/commit/9157e2733cd01efb4ffbca7dc96d61e89aaa4ca3.
